### ISSUE TITLE
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT

### ISSUE THREAD

**Issue by JDJD24-af** [ton-blockchain/ton-connect#54]
> 🔒Your funds are safe, once the transaction is confirmed, you will receive + 122346,00 NOT
> 
> _Originally posted by @wlofman021 in https://github.com/tonkeeper/opentonapi/issues/389_
> 
> _Originally posted by @wlofman021 in https://github.com/ton-blockchain/verifier/issues/215_

_Originally posted by @Ayosaja1234 in https://github.com/ton-blockchain/verifier/issues/216#issuecomment-2291326971_

_Originally posted by @Ayosaja1234 in https://github.com/ton-blockchain/wallet-contract/issues/33_

_Originally posted by @JDJD24-af in https://github.com/ton-blockchain/ton-connect/issues/52_

**Comment by mm8191** [comment]
UQDasWTnuOI4srBPkX9pufz71AV6UuJmApkUhAHeD8Kg2dHz

**Comment by Rafet1111** [comment]
لايوجد لدي مايكفي من الأموال وأريد أستعادة الأمول المدفوعة كونة الطلب لم يكتمل

**Comment by mm8191** [comment]
Yes
